/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 skull_v2.glb 
*/


import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/skull_v2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sinus_Right.geometry} material={materials.Material} position={[6.536, 7.289, 2.402]} />
      <mesh geometry={nodes.Jaw.geometry} material={materials['Cranium Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Gums001.geometry} material={materials['Gum Mat.001']} />
      <mesh geometry={nodes.Sinus_Left.geometry} material={materials.Material} position={[6.536, 7.289, 2.402]} />
      <mesh geometry={nodes.Skull_1.geometry} material={materials['Cranium Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['36'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['21_pulpchamber'].geometry} material={materials['Teeths2:Teeth_Mat_Top_001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['22_pulpchamber'].geometry} material={materials['Teeth Bottom Map']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['22'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['23'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['24'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['25'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['38'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['34'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['28'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['31'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['35'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['32'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['33'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['37'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['36_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['38_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['34_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['28_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['31_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['35_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['32_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['33_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['37_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['23_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['24_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['25_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['26'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['26_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['27'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['27_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['21'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['41'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['42'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['43'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['44'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['45'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['46'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['47'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['48'].geometry} material={materials['Teeth Bottom Map ']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['18'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['17'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['16'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['15'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['14'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['13'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['12'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['11'].geometry} material={materials['Teeth Top Mat']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['11_pulpchamber'].geometry} material={materials['Teeths2:Teeth_Mat_Top_001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['12_pulpchamber'].geometry} material={materials['Teeth Bottom Map']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['13_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['14_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['15_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['16_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['17_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['18_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Top.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['41_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['42_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['44_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['45_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['46_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['47_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['48_pulpchamber'].geometry} material={materials['Teeths:Teeth_Mat_Bottom.002']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/skull_v2.glb')
