/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 teeth21cavity.glb 
*/


import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/teeth21cavity.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="21" geometry={nodes['21'].geometry} material={materials['Teeth Top Mat']} morphTargetDictionary={nodes['21'].morphTargetDictionary} morphTargetInfluences={nodes['21'].morphTargetInfluences} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Cavitie_Teeth_21" geometry={nodes.Cavitie_Teeth_21.geometry} material={nodes.Cavitie_Teeth_21.material} morphTargetDictionary={nodes.Cavitie_Teeth_21.morphTargetDictionary} morphTargetInfluences={nodes.Cavitie_Teeth_21.morphTargetInfluences} position={[10.628, 4.163, -0.902]} scale={0.144} />
    </group>
  )
}

useGLTF.preload('/teeth21cavity.glb')
